version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adsdev123
      MYSQL_DATABASE: crud
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: adsdev123
      DB_NAME: crud
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./frontend:/app

volumes:
  db_data:
