services:
  db:
    image: mysql:8.0
    restart: always
    container_name: api_database
    environment:
      MYSQL_ROOT_PASSWORD: adsdev123
      MYSQL_DATABASE: crud
    ports:
      - "3306:3306"
    networks:
      - app-users
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    restart: always
    container_name: api
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: adsdev123
      DB_NAME: crud
    ports:
      - "8800:8800"
    networks:
      - app-users
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-users
    depends_on:
      - api

volumes:
  db_data:
